# HookProbe Fortress - Grafana Datasource Configuration
# Auto-provisioned at container startup

apiVersion: 1

# Delete existing datasources before re-provisioning to avoid conflicts
deleteDatasources:
  - name: VictoriaMetrics
    orgId: 1
  - name: Fortress-Postgres
    orgId: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    # Use container name (fts-victoria) for DNS resolution within fts-mgmt network
    url: http://fts-victoria:8428
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.40.0"

  - name: Fortress-Postgres
    type: postgres
    # Use container name for DNS resolution within network
    url: fts-postgres:5432
    database: fortress
    user: fortress
    isDefault: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: false
